mod day1;
mod day10;
mod day11;
mod day12;
mod day13;
mod day14;
mod day15;
mod day16;
mod day2;
mod day3;
mod day4;
mod day5;
mod day6;
mod day7;
mod day8;
mod day9;

fn main() {
    println!("****");
    day1::print_depth_incrs();
    println!("****");
    day2::print_position();
    println!("****");
    day3::print_power();
    println!("****");
    day4::display_bingo();
    println!("****");
    day5::print_hydrothermals();
    println!("****");
    day6::print_lanternfishes_counts();
    println!("****");
    day7::print_crab_alignment();
    println!("****");
    day8::display_digits();
    println!("****");
    day9::display_smoke_risks();
    println!("****");
    day10::print_syntax_check();
    println!("****");
    day11::display_octopuses_flash_count();
    println!("****");
    day12::display_pathes();
    println!("****");
    day13::print_origami_details();
    println!("****");
    day14::display_polymer();
    println!("****");
    day15::display_safest_path();
    println!("****");
    day16::print_bits();
}
