mod day1;
mod day10;
mod day11;
mod day12;
mod day13;
mod day14;
mod day15;
mod day16;
mod day17;
mod day18;
mod day19;
mod day2;
mod day20;
mod day21;
mod day22;
mod day23;
mod day24;
mod day3;
mod day4;
mod day5;
mod day6;
mod day7;
mod day8;
mod day9;

fn main() {
    println!("****");
    day1::print_depth_incrs();
    println!("****");
    day2::print_position();
    println!("****");
    day3::print_power();
    println!("****");
    day4::display_bingo();
    println!("****");
    day5::print_hydrothermals();
    println!("****");
    day6::print_lanternfishes_counts();
    println!("****");
    day7::print_crab_alignment();
    println!("****");
    day8::display_digits();
    println!("****");
    day9::display_smoke_risks();
    println!("****");
    day10::print_syntax_check();
    println!("****");
    day11::display_octopuses_flash_count();
    println!("****");
    day12::display_pathes();
    println!("****");
    day13::print_origami_details();
    println!("****");
    day14::display_polymer();
    println!("****");
    day15::display_safest_path();
    println!("****");
    day16::print_bits();
    println!("****");
    day17::display_trajectory();
    println!("****");
    day18::display_additions();
    println!("****");
    day19::display_breacons_and_scanners();
    println!("****");
    // day20::display_enhanced_img();
    println!("****");
    day21::display_dirac_dice_play();
    println!("****");
    day22::display_reactor_reboot();
    println!("****");
    day23::organize_amphipods();
    println!("****");
    day24::print_larget_serial_accepted_by_monad();
}
